[package]
name = "displaykeeper"
version = "0.1.0"
authors = ["Ivan Zub <zub.ivan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core-foundation = "0.6.4"
core-graphics = "0.17.3"