on: [push]

name: build

jobs:
  check:
    name: Rust project
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
